### ISSUE TITLE
AttributeError: type object 'MiniMaxH3ReferenceToVideo' has no attribute '_encode_ref_audio'

### ISSUE THREAD

**Issue by neurodanzelus-cmd** [jlucasmcrell/ComfyUI-H3-Multishot#15]
Need to update method

**Comment by jlucasmcrell** [comment]
Thanks - fixed in v2.6.1. ComfyUI master moved that helper from a static method on `MiniMaxH3ReferenceToVideo` to a module-level function, and the memory sampler was still calling the old location. 2.6.1 resolves whichever one your ComfyUI has, so it works on 0.30-0.33 and on current master.

Update the pack (ComfyUI-Manager -> Update, or `git pull` in `custom_nodes/ComfyUI-H3-Multishot`), restart, and it will run. If you hit anything else on master, paste the traceback here - master moves things between releases and this is exactly the kind of report that keeps the pack current.
